services:
  - type: web
    name: proyecto
    runtime: docker
    plan: free
    branch: main
    envVars:
      - key: APP_NAME
        value: Laravel
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://proyecto-1-wobq.onrender.com
      - key: APP_KEY
        value: base64:oSh+YTk/oBPTUHDtLXfCYoq1xJlLTfy6wqF06+imV0k=
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE
        value: /var/www/html/database/database.sqlite
